# Generated by Django 5.2 on 2025-04-23 02:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Novasen_app', '0001_initial'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Provincia',
            new_name='Provivencia',
        ),
        migrations.DeleteModel(
            name='fomularioDiciplinario',
        ),
        migrations.RenameField(
            model_name='ciudad',
            old_name='provincia',
            new_name='provivencia',
        ),
        migrations.RenameField(
            model_name='fichas',
            old_name='ficha',
            new_name='numero_ficha',
        ),
        migrations.RenameField(
            model_name='provivencia',
            old_name='provincia',
            new_name='provivencia',
        ),
        migrations.AlterField(
            model_name='fichas',
            name='ambiente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Novasen_app.ambiente'),
        ),
        migrations.AlterField(
            model_name='fichas',
            name='nombre',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='groups',
            field=models.ManyToManyField(blank=True, related_name='novasen_app_users', to='auth.group'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, related_name='novasen_app_permissions', to='auth.permission'),
        ),
    ]
